# Writing my own CircleCI YML

version: 2.1

jobs:
  build-and-test:
    docker:
      image: oven/bun:latest
    resource_class: small # Don't forget to define the resource allocation to save credit

    steps:
      - checkout

      - restore_cache:
          keys:
            - bun-{{ checksum "bun.lock" }}
            - bun-

      - run:
          name: Install dependencies
          command: bun install --frozen-lockfile

      - save_cache:
          key: bun-{{ checksum "bun.lock" }}
          paths:
            - ~/.bun/install/cache

      - run:
          name: Run tests
          command: bun test

# TODO: Add coverage reporting using Codecov.

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
